[package]
name = "solana-coverage"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/procdump/solana-coverage.git"
readme = "README.md"

[dependencies]
solana-program-stubs = "0.1.0"
